import React from 'react';
import{Activity,Brain,GitBranch,Home,Kanban,MessageSquare,Settings,Shield,Terminal,Boxes,SlidersHorizontal,Workflow}from'lucide-react';
import{AgentKey}from'../../api/types';
import{StatusDot,cls}from'../primitives/Card';

export type PageKey='mission'|'workspaces'|'kanban'|'memory'|'skills'|'canvas'|'activity'|'settings'|'codex'|'deepseek'|'claude'|'hermes';
const workspace=[['mission','Mission Control',Home],['workspaces','Workspaces',GitBranch],['kanban','Kanban',Kanban],['memory','Memory',Brain],['skills','Skills Hub',Shield],['canvas','Canvas',Workflow],['activity','Activity',Activity],['settings','Settings',Settings]] as const;
const agents=[['codex','Codex','runtime checked',Terminal],['deepseek','DeepSeek','runtime checked',MessageSquare],['claude','Claude','disabled until configured',Boxes],['hermes','Hermes','runtime checked',SlidersHorizontal]] as const;
export const pageTitles:Record<PageKey,string>={mission:'Mission Control',workspaces:'Workspaces',kanban:'Kanban',memory:'Memory',skills:'Skills Hub',canvas:'Canvas',activity:'Activity',settings:'Settings',codex:'Codex Room',deepseek:'DeepSeek Room',claude:'Claude Room',hermes:'Hermes Room'};
export function Sidebar({page,setPage,compact=false}:{page:PageKey;setPage:(p:PageKey)=>void;compact?:boolean}){return <aside className={cls('sidebar',compact&&'compact')}><button className='brand' onClick={()=>setPage('mission')}><span className='brand-mark'/><span><b>Agentic OS</b><small>one process, every door</small></span></button><div className='nav-group'><p>Workspace</p>{workspace.map(([key,label,Icon])=><button key={key} className={cls('nav-item',page===key&&'active')} onClick={()=>setPage(key as PageKey)}><Icon size={18}/><span>{label}</span></button>)}</div><div className='nav-group'><p>Agent rooms</p>{agents.map(([key,label,state,Icon])=><button key={key} className={cls('nav-item',page===key&&'active',`agent-${key}`)} onClick={()=>setPage(key as PageKey)}><Icon size={18}/><span>{label}<small><StatusDot status={state} agent={key}/>{state}</small></span></button>)}</div><div className='sidebar-note'>Local studio mode. Admin actions require the browser token and remain audit logged.</div></aside>}
