import{Activity,Brain,GitBranch,Home,Kanban,MessageSquare,Settings,Shield,Terminal,Boxes,SlidersHorizontal,Workflow,Bot,Sparkles}from'lucide-react';
import{AgentDefinition,EffectiveSettings}from'../../api/types';import{useData}from'../../app/hooks';
import{StatusDot,cls}from'../primitives/Card';

export type PageKey='mission'|'agents'|'workspaces'|'kanban'|'memory'|'skills'|'canvas'|'activity'|'settings'|'codex'|'deepseek'|'claude'|'hermes';
const workspace=[['mission','Mission Control',Home],['agents','Agents',Bot],['workspaces','Workspaces',GitBranch],['kanban','Kanban',Kanban],['memory','Memory',Brain],['skills','Skills Hub',Shield],['canvas','Canvas',Workflow],['activity','Activity',Activity],['settings','Settings',Settings]] as const;
const runtimeRooms=[['codex','Codex','runtime checked',Terminal],['deepseek','DeepSeek','runtime checked',MessageSquare],['claude','Claude','disabled until configured',Boxes],['hermes','Hermes','runtime checked',SlidersHorizontal]] as const;
const builtIns=new Set(['codex-worker','deepseek-chat','claude-code','hermes-control','mcp-registry']);
export const pageTitles:Record<PageKey,string>={mission:'Mission Control',agents:'Agents',workspaces:'Workspaces',kanban:'Kanban',memory:'Memory',skills:'Skills Hub',canvas:'Canvas',activity:'Activity',settings:'Settings',codex:'Codex Room',deepseek:'DeepSeek Room',claude:'Claude Room',hermes:'Hermes Room'};
export function Sidebar({page,setPage,compact=false}:{page:PageKey;setPage:(p:PageKey)=>void;compact?:boolean}){const settings=useData<EffectiveSettings>('/settings/effective',7000);const customAgents=(settings.data?.agents||[]).filter((a:AgentDefinition)=>!builtIns.has(a.name));return <aside className={cls('sidebar',compact&&'compact')}><button className='brand' onClick={()=>setPage('mission')}><span className='brand-mark'/><span><b>Agentic OS</b><small>one process, every door</small></span></button><div className='nav-group'><p>Control plane</p>{workspace.map(([key,label,Icon])=><button key={key} className={cls('nav-item',page===key&&'active')} onClick={()=>setPage(key as PageKey)}><Icon size={18}/><span>{label}</span></button>)}</div><div className='nav-group'><p>Runtime rooms</p>{runtimeRooms.map(([key,label,state,Icon])=><button key={key} className={cls('nav-item',page===key&&'active',`agent-${key}`)} onClick={()=>setPage(key as PageKey)}><Icon size={18}/><span>{label}<small><StatusDot status={state} agent={key}/>{state}</small></span></button>)}</div><div className='nav-group'><p>Custom agents</p>{!customAgents.length&&<button className='nav-item' onClick={()=>setPage('agents')}><Sparkles size={18}/><span>Create agent<small>provider · memory · workspace · tools</small></span></button>}{customAgents.map((agent:AgentDefinition)=><button key={agent.name} className={cls('nav-item',page==='agents'&&'active')} onClick={()=>setPage('agents')}><Sparkles size={18}/><span>{agent.label||agent.name}<small><StatusDot status={agent.enabled===false?'disabled':'ready'} agent='hermes'/>{agent.provider||'provider'} · {agent.model||'model strategy'}</small></span></button>)}</div><div className='sidebar-note'>Local studio mode. Build agents by selecting provider, workspace, memory, skills/MCP, approvals, then assign tasks.</div></aside>}
