import React from 'react';
import {AlertTriangle, ArrowRight, CheckCircle2, CircleDashed, LockKeyhole, Play, ShieldCheck, Sparkles, XCircle} from 'lucide-react';
import {Badge, Button, Card, cls} from '../primitives/Card';
import type {AuditEvent, KanbanTask, SystemStatus} from '../../api/types';
export const R = String.fromCharCode(47);
export const agentMeta: Record<string,{label:string;role:string;mode:string;tone:'codex'|'deepseek'|'claude'|'hermes';summary:string}>={deepseek:{label:'DeepSeek',role:'Reasoning and research agent',mode:'cloud_api',tone:'deepseek',summary:'Cloud API with live model selection. Best for reasoning, summaries, UI copy, research, and low-risk planning.'},codex:{label:'Codex',role:'Implementation agent',mode:'subscription_cli',tone:'codex',summary:'Subscription CLI adapter for code changes, tests, diffs, and auditable implementation work.'},claude:{label:'Claude Code',role:'Premium implementation lane',mode:'subscription_cli',tone:'claude',summary:'Subscription CLI adapter model for deep implementation/review when configured.'},hermes:{label:'Hermes',role:'Orchestration and local tools',mode:'remote_api / local_cli',tone:'hermes',summary:'Callable gateway/API or deliberate CLI bridge. Dashboard-only URLs are not capability access.'}};
export const flow=['Space','Agent','Provider/model','Workspace','Memory','Skills/MCP','Work Order','Approval','Run','Artifact/Audit'];
export function statusTone(status?:string,ready?:boolean){const s=(status||'').toLowerCase();if(ready||s.includes('ready')||s.includes('ok')||s.includes('healthy'))return 'success';if(s.includes('block')||s.includes('missing')||s.includes('disabled')||s.includes('not'))return 'warning';if(s.includes('fail')||s.includes('error'))return 'danger';return 'neutral'}
export function readinessLabel(s?:SystemStatus){if(!s)return 'not configured';if(s.ready)return 'ready';if(s.enabled===false)return 'disabled';return s.status||'blocked'}
export function OperatingFlowStrip({active}:{active?:string}){return <div className='ops-flow'>{flow.map((step,i)=><React.Fragment key={step}><div className={cls('ops-step',active===step&&'active')}><span>{i+1}</span><strong>{step}</strong><small>{i<3?'configure':i<6?'connect':i<8?'control':'evidence'}</small></div>{i<flow.length-1&&<ArrowRight className='ops-arrow' size={16}/>}</React.Fragment>)}</div>}
export function ConnectionBanner({system,agent}:{system?:SystemStatus;agent:string}){const meta=agentMeta[agent]||agentMeta.hermes;const tone=statusTone(system?.status,system?.ready);const ready=system?.ready;const Icon=ready?CheckCircle2:tone==='danger'?XCircle:AlertTriangle;return <Card className={cls('connection-banner',`agent-${meta.tone}`)}><div className='connection-main'><Icon size={22}/><div><p className='eyebrow'>{meta.mode}</p><h3>{meta.label} connection</h3><p>{ready?'Action path is ready for this adapter.':system?.detail||'Action path is not ready yet. Configure and test before run/chat controls become active.'}</p></div></div><div className='connection-actions'><Badge tone={tone as any}>{readinessLabel(system)}</Badge><Button variant='secondary'>Test connection</Button></div></Card>}
export function SetupBlockerCard({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <Card className='setup-blocker'><div><AlertTriangle size={18}/><strong>{title}</strong></div><p>{body}</p>{action}</Card>}
export function RuntimeHealthCard({system,onOpen}:{system:SystemStatus;onOpen?:()=>void}){const key=system.adapter_key||system.name;const meta=agentMeta[key]||{label:system.display_name||system.name,mode:system.connection_mode||system.mode||'adapter',tone:'hermes',summary:system.detail||''};return <Card className={cls('runtime-card',`agent-${meta.tone}`)}><div className='runtime-head'><div><p className='eyebrow'>{meta.mode}</p><h3>{meta.label}</h3></div><Badge tone={statusTone(system.status,system.ready) as any}>{readinessLabel(system)}</Badge></div><p>{system.detail||meta.summary}</p><div className='runtime-meta'><span>Provider: {system.provider||system.name}</span><span>Mode: {system.connection_mode||system.mode||meta.mode}</span><span>Last probe: {system.latest_activity||'not recorded'}</span></div><div className='card-actions'><Button variant='secondary' onClick={onOpen}>Open room</Button><Button variant='ghost'>Test</Button></div></Card>}
export function WorkMotionCard({task,onOpen}:{task:KanbanTask;onOpen?:()=>void}){const agent=task.agent||task.assigned_agent||'unassigned';const runtime=task.runtime;const runnable=runtime?.ready&&task.approval_state==='approved';return <Card className='work-motion-card'><div className='work-card-head'><div><strong>{task.title}</strong><p>{task.description||'No description yet. Add intent, constraints, expected artifact, and validation command.'}</p></div><Badge tone={statusTone(task.status,runnable) as any}>{task.status}</Badge></div><div className='chip-row'><span>{agent}</span><span>{task.workspace||'no workspace'}</span><span>{task.memory_scope||'memory unset'}</span><span>{task.approval_state||'needs approval'}</span></div><div className='work-card-footer'><small>{task.validation_command||'No validation command'}</small><Button variant='secondary' onClick={onOpen}>Open detail</Button></div></Card>}
export function EvidenceTimeline({events}:{events:AuditEvent[]}){if(!events.length)return <Card><div className='empty-inline'><CircleDashed size={18}/><span>No audit events yet. Runtime tests, approvals, runs, blockers, and artifacts will appear here.</span></div></Card>;return <div className='evidence-timeline'>{events.slice(0,10).map((e,i)=><Card key={e.id||i} className='audit-event-card'><div className='timeline-dot'/><div><strong>{humanAction(e)}</strong><p>{e.error||`${e.target_agent||'system'} · ${e.workspace||'workspace not set'} · ${e.status}`}</p><small>{e.timestamp||'no timestamp'}</small></div><Badge tone={statusTone(e.status) as any}>{e.status}</Badge></Card>)}</div>}
function humanAction(e:AuditEvent){const re=new RegExp('[_-]','g');const a=(e.action||'event').replace(re,' ');return a.charAt(0).toUpperCase()+a.slice(1)}
export function ReadinessChecklist({items}:{items:{label:string;ok:boolean;detail:string}[]}){return <div className='readiness-list'>{items.map(item=><div key={item.label} className={cls('readiness-item',item.ok?'ok':'blocked')}><span>{item.ok?<CheckCircle2 size={16}/>:<LockKeyhole size={16}/>}</span><div><strong>{item.label}</strong><small>{item.detail}</small></div></div>)}</div>}
export function AgentHeader({agent,system}:{agent:string;system?:SystemStatus}){const meta=agentMeta[agent]||agentMeta.hermes;return <section className={cls('agent-room-hero',`agent-${meta.tone}`)}><div><p className='eyebrow'>agent room</p><h2>{meta.label}</h2><p>{meta.summary}</p><div className='chip-row'><span>Role: {meta.role}</span><span>Adapter: {meta.mode}</span><span>Status: {readinessLabel(system)}</span><span>Approval: ask-before-run</span></div></div><div className='agent-room-orb'><Sparkles size={28}/></div></section>}
export function PageHero({eyebrow,title,body,children}:{eyebrow:string;title:string;body:string;children?:React.ReactNode}){return <section className='mission-hero polished-hero'><div><p className='eyebrow'>{eyebrow}</p><h2>{title}</h2><p>{body}</p></div>{children&&<div className='mission-actions'>{children}</div>}</section>}
export function ActionGate({ready,reason}:{ready:boolean;reason:string}){return <Card className={ready?'action-gate ready':'action-gate blocked'}><div><ShieldCheck size={20}/><strong>{ready?'Execution gate open':'Execution gate blocked'}</strong></div><p>{ready?'Runtime readiness, approval, and workspace checks allow action.':reason}</p><Button disabled={!ready}><Play size={14}/> Run</Button></Card>}
