import React from 'react';
import{KanbanTask}from'../../api/types';import{patch,post}from'../../api/client';import{Badge as UIBadge,Button as UIButton,Card as UICard,EmptyState as UIEmptyState}from'../primitives/Card';
const h=React.createElement;
const CardAny=UICard as any;const BadgeAny=UIBadge as any;const ButtonAny=UIButton as any;const EmptyAny=UIEmptyState as any;
const columns=['Backlog','Ready','Running','Review','Done','Failed'];
const API=String.fromCharCode(47);
function badgeTone(status?:string){const s=(status||'').toLowerCase();if(s.includes('ready')||s.includes('completed')||s==='approved')return'success';if(s.includes('block')||s.includes('fail'))return'danger';if(s.includes('need')||s.includes('running'))return'warning';return'neutral'}
export function KanbanCard({task,onMove,onRun,onApprove}:{task:KanbanTask;onMove:(status:string)=>void;onRun:()=>void;onApprove:()=>void}){const runtime=task.runtime;const agent=task.agent||task.assigned_agent;const canRun=task.approval_state==='approved'&&!!runtime?.ready;return h(CardAny,{className:'kanban-card'},h('div',{className:'card-title-row'},h('h3',null,task.title),h(BadgeAny,{tone:badgeTone(task.approval_state)},task.approval_state||'needs_approval')),task.description?h('p',null,task.description):null,h('div',{className:'chip-row'},agent?h(BadgeAny,{tone:(runtime?.adapter_key as any)||'neutral'},agent):null,task.capability_id?h(BadgeAny,null,task.capability_id):null,task.workspace?h(BadgeAny,null,task.workspace):null,task.memory_scope?h(BadgeAny,null,`memory: ${task.memory_scope}`):null,task.run_session_id?h(BadgeAny,{tone:'codex'},'session linked'):null),runtime?h('div',{className:'runtime-mini'},h('strong',null,runtime.ready?'Runtime ready':'Runtime blocked'),h('span',null,runtime.detail||runtime.status)):null,task.validation_command?h('small',null,`Validation: ${task.validation_command}`):null,h('small',null,`Updated ${task.updated_at||task.created_at||'unknown'}`),h('div',{className:'move-row'},h(ButtonAny,{variant:'ghost',onClick:onApprove,disabled:task.approval_state==='approved'},'Approve'),h(ButtonAny,{variant:canRun?'primary':'ghost',onClick:onRun,disabled:!canRun},'Run'),...columns.filter(c=>c!==task.status).slice(0,2).map(c=>h(ButtonAny,{key:c,variant:'ghost',onClick:()=>onMove(c)},`Move ${c}`))),!canRun&&task.approval_state==='approved'&&runtime&&!runtime.ready?h('p',{className:'error-panel small'},`Run blocked: ${runtime.detail}`):null)}
export function KanbanColumn({title,tasks,onChanged}:{title:string;tasks:KanbanTask[];onChanged:()=>void}){async function move(id:string,status:string){await patch(API+`kanban/tasks/${id}`,{status});onChanged()}async function approve(id:string){await post(API+`kanban/tasks/${id}`+API+'approve',{});onChanged()}async function run(id:string){await post(API+`kanban/tasks/${id}`+API+'run',{});onChanged()}return h('section',{className:'kanban-column'},h('h2',null,title,h(BadgeAny,null,tasks.length)),tasks.map(t=>h(KanbanCard,{key:t.id,task:t,onMove:(s:string)=>move(t.id,s),onApprove:()=>approve(t.id),onRun:()=>run(t.id)})),!tasks.length?h(EmptyAny,{title:'Empty lane',body:`No ${title.toLowerCase()} work orders.`}):null)}
export function KanbanBoard({tasks,onChanged}:{tasks:KanbanTask[];onChanged:()=>void}){return h('div',{className:'kanban-board'},columns.map(c=>h(KanbanColumn,{key:c,title:c,tasks:tasks.filter(t=>t.status===c),onChanged}))) }
