import React from 'react';
export function cls(...parts:(string|false|undefined|null)[]){return parts.filter(Boolean).join(' ')}
export function Card({children,className='',tone=''}:{children:React.ReactNode;className?:string;tone?:string}){return <div className={cls('card',tone&&`tone-${tone}`,className)}>{children}</div>}
export function Button({children,variant='primary',className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'|'agent'}){return <button className={cls('btn',`btn-${variant}`,className)} {...props}>{children}</button>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'codex'|'deepseek'|'claude'|'hermes'}){return <span className={cls('badge',`badge-${tone}`)}>{children}</span>}
export function StatusDot({status='unknown',agent}:{status?:string;agent?:string}){const s=(status||'').toLowerCase();const tone=s.includes('fail')||s.includes('error')?'danger':s.includes('run')||s.includes('ok')||s.includes('enable')||s.includes('healthy')?'success':s.includes('disable')?'muted':agent||'neutral';return <span className={cls('status-dot',`dot-${tone}`)} />}
export function EmptyState({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div className="empty-state"><div className="empty-orb"/><h3>{title}</h3><p>{body}</p>{action}</div>}
export function MetricCard({label,value,accent='hermes',hint}:{label:string;value:React.ReactNode;accent?:string;hint?:string}){return <Card className="metric-card"><span className={`metric-accent accent-${accent}`}/><p>{label}</p><strong>{value}</strong>{hint&&<small>{hint}</small>}</Card>}
export function SectionHeader({eyebrow,title,children}:{eyebrow?:string;title:string;children?:React.ReactNode}){return <div className="section-header"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div><div className="section-actions">{children}</div></div>}
export function AdvancedRaw({data,label='Advanced raw data'}:{data:any;label?:string}){return <details className="advanced-raw"><summary>{label}</summary><pre>{JSON.stringify(data,null,2)}</pre></details>}
