import{Activity,Boxes,Brain,Cpu,Database,FileCode,GitBranch,KeyRound,Network,PackageCheck,Rocket,ShieldCheck,Timer,Workflow}from'lucide-react';
import{useData}from'../app/hooks';
import{Badge,Card,EmptyState,SectionHeader}from'../components/primitives/Card';

type Capability={id?:string;name:string;description?:string;owning_agent?:string;allowed_models?:string[];allowed_tools_mcps?:string[];allowed_workspaces?:string[];memory_scope?:string;prompt?:string;approval_gates?:string[];audit_policy?:string;schedule?:{supported?:boolean};generated_artifacts?:string[];rollback_notes?:string};
type EffectiveSettings={capabilities?:Capability[];spaces?:{id?:string;name:string;description?:string;capabilities?:string[]}[]};
type CanvasNode={id:string;type:string;label:string;description?:string};
type CanvasEdge={source:string;target:string;label:string};
const icons:Record<string,any>={Agent:Cpu,Model:Brain,Prompt:FileCode,'Tool/MCP':Network,API:Activity,Workspace:GitBranch,Memory:Database,Approval:ShieldCheck,Audit:KeyRound,Artifact:PackageCheck,Schedule:Timer,'Deployment Target':Rocket,Capability:Workflow};
const order=['Capability','Agent','Model','Prompt','Tool/MCP','API','Workspace','Memory','Approval','Audit','Artifact','Schedule','Deployment Target'];
function graph(settings?:EffectiveSettings){const nodes:Record<string,CanvasNode>={};const edges:CanvasEdge[]=[];const add=(node:CanvasNode)=>{nodes[node.id]=node};for(const space of settings?.spaces||[]){const sid=`space:${space.id||space.name}`;add({id:sid,type:'Workspace',label:space.name,description:space.description});for(const cap of space.capabilities||[])edges.push({source:sid,target:`capability:${cap}`,label:'groups'})}for(const cap of settings?.capabilities||[]){const cid=cap.id||cap.name;const capId=`capability:${cid}`;add({id:capId,type:'Capability',label:cap.name,description:cap.description});const agent=cap.owning_agent||'unknown';add({id:`agent:${agent}`,type:'Agent',label:agent});edges.push({source:capId,target:`agent:${agent}`,label:'owned by'});add({id:`prompt:${cid}`,type:'Prompt',label:`Prompt policy: ${cap.name}`,description:cap.prompt});edges.push({source:capId,target:`prompt:${cid}`,label:'uses'});add({id:`api:${cid}`,type:'API',label:'Runtime/API boundary',description:'Actions must enter through Agentic OS APIs and adapter gates.'});edges.push({source:capId,target:`api:${cid}`,label:'controlled by'});for(const model of cap.allowed_models||[]){add({id:`model:${model}`,type:'Model',label:model});edges.push({source:capId,target:`model:${model}`,label:'allowed model'})}for(const tool of cap.allowed_tools_mcps||[]){add({id:`tool:${tool}`,type:'Tool/MCP',label:tool});edges.push({source:capId,target:`tool:${tool}`,label:'allowed tool'})}for(const workspace of cap.allowed_workspaces||[]){add({id:`workspace:${workspace}`,type:'Workspace',label:workspace});edges.push({source:capId,target:`workspace:${workspace}`,label:'allowed workspace'})}const memory=cap.memory_scope||'none';add({id:`memory:${memory}`,type:'Memory',label:`Memory: ${memory}`});edges.push({source:capId,target:`memory:${memory}`,label:'memory scope'});for(const gate of cap.approval_gates||[]){add({id:`approval:${cid}:${gate}`,type:'Approval',label:gate});edges.push({source:capId,target:`approval:${cid}:${gate}`,label:'requires'})}add({id:`audit:${cid}`,type:'Audit',label:cap.audit_policy||'Audit required'});edges.push({source:capId,target:`audit:${cid}`,label:'records'});if(cap.schedule?.supported){add({id:`schedule:${cid}`,type:'Schedule',label:'Schedule supported'});edges.push({source:capId,target:`schedule:${cid}`,label:'can schedule'})}for(const artifact of cap.generated_artifacts||[]){add({id:`artifact:${cid}:${artifact}`,type:'Artifact',label:artifact});edges.push({source:capId,target:`artifact:${cid}:${artifact}`,label:'generates'})}if(cap.rollback_notes){add({id:`deploy:${cid}`,type:'Deployment Target',label:'Rollback/deployment policy',description:cap.rollback_notes});edges.push({source:capId,target:`deploy:${cid}`,label:'rollback'})}}return{nodes:Object.values(nodes),edges}}
export function Canvas(){const{data,error,loading}=useData<EffectiveSettings>('/settings/effective',15000);const g=graph(data||undefined);const grouped=order.map(type=>[type,g.nodes.filter(n=>n.type===type)] as const).filter(([,items])=>items.length);const connected=(id:string)=>g.edges.filter(e=>e.source===id||e.target===id).slice(0,4);return <div className='page-stack'><section className='mission-hero'><div><p className='eyebrow'>visual workflow cockpit</p><h2>Canvas</h2><p>View-only workflow map generated from Capability YAML through effective settings. This is not a fake drag/drop editor; editing comes later.</p></div><div className='mission-actions'><Badge tone='warning'>view-only canvas</Badge><Badge>config/capabilities.yaml</Badge></div></section>{error&&<p className='error-panel'>{error}</p>}{loading&&!data&&<Card>Loading capability graph…</Card>} {!loading&&g.nodes.length===0&&<EmptyState title='No capabilities loaded' body='Add config/capabilities.yaml entries to render the operating graph.'/>}<SectionHeader eyebrow='graph summary' title={`${g.nodes.length} nodes / ${g.edges.length} edges`}/><div className='dashboard-grid'>{grouped.map(([type,items])=>{const Icon=icons[type]||Boxes;return <Card key={type}><h3><Icon size={18}/> {type}</h3>{items.map(node=><div key={node.id} className='advanced-raw'><strong>{node.label}</strong>{node.description&&<p>{node.description}</p>}<div className='chip-row'>{connected(node.id).map((e,i)=><Badge key={i}>{e.source===node.id?'→':'←'} {e.label}</Badge>)}</div></div>)}</Card>})}</div></div>}
