import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,Brain,GitBranch,Home,Kanban as KanbanIcon,MessageSquare,Settings,Shield,Terminal,Target,Plug,ChevronRight,Boxes,CheckCircle2,AlertTriangle}from'lucide-react';
import{get,post}from'./api/client';
import'./styles/app.css';

type NavItem={label:string;page:string;desc:string};
type Agent={key:string;label:string;tagline:string;icon:any;items:NavItem[]};
const agents:Agent[]=[
  {key:'codex',label:'Codex',tagline:'code worker: run, review, commit, push',icon:Terminal,items:[
    {label:'Control Room',page:'Codex Control Room',desc:'Start audited codex exec jobs'},
    {label:'Sessions',page:'Codex Sessions',desc:'Running/history/logs/cancel/commit'},
    {label:'Workspaces',page:'Workspaces',desc:'Allowed repos and git status'},
    {label:'Activity',page:'Activity',desc:'Codex audit trail'}]},
  {key:'hermes',label:'Hermes',tagline:'orchestrator: MCP, sessions, workspaces, kanban, memory',icon:Brain,items:[
    {label:'Mission Control',page:'Mission Control',desc:'All agent/process status'},
    {label:'Capabilities',page:'Hermes Capabilities',desc:'What Hermes can do and what is wired'},
    {label:'MCPs',page:'MCPs',desc:'MCP registry and add/remove state'},
    {label:'Chat Sessions',page:'Chat Sessions',desc:'Stored chat threads'},
    {label:'Workspaces',page:'Workspaces',desc:'Workspace registry/status'},
    {label:'Kanban',page:'Kanban',desc:'Task board'},
    {label:'Memory',page:'Memory',desc:'Local memories'},
    {label:'Skills Hub',page:'Skills Hub',desc:'Available skills'},
    {label:'Goals',page:'Goals',desc:'Goal records / orchestration scaffold'},
    {label:'Activity',page:'Activity',desc:'Audit timeline'},
    {label:'Settings',page:'Settings',desc:'Effective non-secret config'}]},
  {key:'deepseek',label:'DeepSeek',tagline:'LLM/provider: OpenAI-compatible chat and threads',icon:MessageSquare,items:[
    {label:'Chat',page:'DeepSeek Chat',desc:'Send messages through configured provider'},
    {label:'Threads',page:'Chat Sessions',desc:'Browse chat history'},
    {label:'Provider Settings',page:'Settings',desc:'Provider registry and env requirements'},
    {label:'Activity',page:'Activity',desc:'Chat/provider audit trail'}]},
];
const pageIcon:any={'Mission Control':Home,'Hermes Capabilities':Boxes,'Codex Control Room':Terminal,'Codex Sessions':Terminal,'DeepSeek Chat':MessageSquare,'Chat Sessions':MessageSquare,Workspaces:GitBranch,Kanban:KanbanIcon,Memory:Brain,'Skills Hub':Shield,Activity:Activity,Settings:Settings,Goals:Target,MCPs:Plug};
const pageTitle:any={'Codex Control Room':'Codex Control Room','Codex Sessions':'Codex Sessions','DeepSeek Chat':'DeepSeek Chat','Chat Sessions':'Chat Sessions','Hermes Capabilities':'Hermes Capabilities'};

function Shell(){const[agent,setAgent]=useState('hermes');const activeAgent=agents.find(a=>a.key===agent)!;const[page,setPage]=useState(activeAgent.items[0].page);useEffect(()=>{const a=agents.find(x=>x.key===agent)!;if(!a.items.some(i=>i.page===page))setPage(a.items[0].page)},[agent]);const I=activeAgent.icon;return <div className="shell"><aside><div className="brand"><div className="orb"/><div><b>Agentic OS</b><span>Three agents, wired functions</span></div></div><div className="agent-switch">{agents.map(a=>{const A=a.icon;return <button key={a.key} className={agent===a.key?'active agentbtn':'agentbtn'} onClick={()=>setAgent(a.key)}><A size={18}/><span>{a.label}</span></button>})}</div><div className="agent-card"><I size={22}/><div><b>{activeAgent.label}</b><span>{activeAgent.tagline}</span></div></div><nav>{activeAgent.items.map(n=>{const NI=pageIcon[n.page]||ChevronRight;return <button className={page===n.page?'active':''} onClick={()=>setPage(n.page)} key={n.label}><NI size={17}/><span>{n.label}<small>{n.desc}</small></span></button>})}</nav><div className="hint">Synology: open via <b>NAS-LAN-IP:3737</b>. Backend binds <b>0.0.0.0</b>.</div></aside><main><header><div><p className="eyebrow">{activeAgent.label} / {pageTitle[page]||page}</p><h1>{pageTitle[page]||page}</h1><p>{activeAgent.tagline}. Sidebar items are grouped by agent and route to real pages/API state.</p></div><TokenBox/></header><Page name={page} agent={agent}/></main></div>}
function TokenBox(){const[t,setT]=useState(localStorage.getItem('agentic_token')||'');return <label className="token">Admin token<input type="password" value={t} onChange={e=>{setT(e.target.value);localStorage.setItem('agentic_token',e.target.value)}} placeholder="required for actions"/></label>}
function Page({name,agent}:{name:string;agent:string}){if(name==='Mission Control')return <Mission/>; if(name==='Hermes Capabilities')return <HermesCapabilities/>; if(name==='DeepSeek Chat')return <Chat defaultAgent="deepseek-chat"/>; if(name==='Chat Sessions')return <ChatSessions/>; if(name==='Codex Control Room')return <Codex mode="run"/>; if(name==='Codex Sessions')return <Codex mode="sessions"/>; if(name==='Workspaces')return <List title="Workspaces" path="/workspaces"/>; if(name==='Kanban')return <KanbanPage/>; if(name==='Memory')return <Memory/>; if(name==='Skills Hub')return <List title="Skills" path="/skills"/>; if(name==='Activity')return <Audit agent={agent}/>; if(name==='Goals')return <Goals/>; if(name==='MCPs')return <MCPs/>; return <SettingsPage/>}
function useData(path:string, interval=0){const[d,setD]=useState<any>(null),[e,setE]=useState('');const refresh=()=>get(path).then(x=>{setD(x);setE('')}).catch(x=>setE(String(x)));useEffect(()=>{refresh(); if(interval){const id=setInterval(refresh,interval); return()=>clearInterval(id)}},[path,interval]);return{d,e,refresh}}
function Json({data}:{data:any}){return <pre>{JSON.stringify(data,null,2)}</pre>}
function StateBadge({status}:{status:string}){const ok=status.startsWith('wired');return <span className={ok?'badge ok':'badge warn'}>{ok?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>} {status}</span>}
function Mission(){const{d,e}=useData('/systems/status',5000);return <section>{e&&<p className="err">{e}</p>}<div className="grid">{(d?.systems||[]).map((s:any)=><div className="card" key={s.name}><span className={s.enabled?'dot ok':'dot'}/><h3>{s.name}</h3><p>{s.provider}</p><b>{s.enabled?'Enabled':'Disabled'}</b><small>Sessions {s.active_sessions}</small></div>)}</div><div className="twocol wide"><div className="panel"><h2>Active processes</h2><Json data={d?.active_processes||[]}/></div><div className="panel"><h2>Recent failed actions</h2><Json data={d?.recent_failed_actions||[]}/></div></div></section>}
function HermesCapabilities(){const{d,e,refresh}=useData('/hermes/capabilities',5000);return <section>{e&&<p className="err">{e}</p>}<div className="panel hero"><div><h2>Hermes control surface</h2><p>This is the Hermes-owned area. It shows what exists now, what is configured/running in this Agentic OS instance, and what add/remove controls are currently backed by APIs.</p></div><button onClick={refresh}>Refresh live state</button></div><div className="twocol"><div className="panel"><h2>Running here</h2><Json data={d?.running_here}/></div><div className="panel"><h2>Configured registries</h2><Json data={d?.configured}/></div></div><div className="grid">{(d?.capabilities||[]).map((c:any)=><div className="card capability" key={c.name}><h3>{c.name}</h3><StateBadge status={c.status}/><p>{c.notes||'Backed by the Agentic OS backend API.'}</p><small>{(c.api||[]).join(' · ')||'No Agentic OS API yet'}</small></div>)}</div></section>}
function List({title,path}:{title:string,path:string}){const{d,e,refresh}=useData(path);return <section className="panel"><div className="bar"><h2>{title}</h2><button onClick={refresh}>Refresh</button></div>{e&&<p className="err">{e}</p>}<Json data={d}/></section>}
function ChatSessions(){const{d,e,refresh}=useData('/chat/threads');return <section className="panel"><div className="bar"><h2>Chat Sessions</h2><button onClick={refresh}>Refresh</button></div><p>These are real stored chat threads from the local SQLite database. Open DeepSeek / Chat to send into a thread.</p>{e&&<p className="err">{e}</p>}<Json data={d}/></section>}
function Chat({defaultAgent='deepseek-chat'}:{defaultAgent?:string}){const[threads,setThreads]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[msg,setMsg]=useState(''),[agent,setAgent]=useState(defaultAgent),[thread,setThread]=useState(''),[err,setErr]=useState('');const loadThreads=()=>get('/chat/threads').then(setThreads);useEffect(()=>{loadThreads()},[]);useEffect(()=>{if(thread)get('/chat/threads/'+thread).then(r=>setMessages(r.messages||[]))},[thread]);const send=async()=>{setErr('');try{const r=await post('/chat',{message:msg,agent,thread_id:thread||undefined});setThread(r.thread_id);setMsg('');await loadThreads();const t=await get('/chat/threads/'+r.thread_id);setMessages(t.messages||[])}catch(e:any){setErr(String(e))}};return <section className="twocol"><div className="panel"><h2>Threads</h2>{threads.map(t=><button className="rowbtn" key={t.id} onClick={()=>setThread(t.id)}>{t.title}<small>{t.agent} · {t.model}</small></button>)}</div><div className="panel"><h2>OpenAI-compatible Chat</h2><input value={agent} onChange={e=>setAgent(e.target.value)} placeholder="agent"/><div className="chatbox">{messages.map(m=><div className={'msg '+m.role} key={m.id}><b>{m.role}</b><p>{m.content}</p></div>)}</div><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Ask DeepSeek/OpenWebUI..."/><button onClick={send}>Send</button>{err&&<p className="err">{err}</p>}</div></section>}
function Codex({mode}:{mode:'run'|'sessions'}){const[task,setTask]=useState(''),[workspace,setWorkspace]=useState('agentic-os'),[branch,setBranch]=useState(''),[test,setTest]=useState(''),[selected,setSelected]=useState(''),[commitMsg,setCommitMsg]=useState('');const sessions=useData('/codex/sessions',3000);const session=useData(selected?'/codex/sessions/'+selected:'/codex/sessions',selected?2000:0);const run=async()=>{const r=await post('/codex/run',{task,workspace,branch:branch||undefined,test_command:test||undefined,auto_commit:false,background:true});setSelected(r.id)};const cancel=()=>selected&&post('/codex/sessions/'+selected+'/cancel',{});const commit=()=>selected&&post('/codex/sessions/'+selected+'/commit',{confirm:true,message:commitMsg||'codex: apply session changes'});return <section className="twocol"><div className="panel"><h2>{mode==='run'?'Start Codex task':'Codex sessions'}</h2>{mode==='run'&&<><input value={workspace} onChange={e=>setWorkspace(e.target.value)} placeholder="workspace"/><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="branch optional"/><input value={test} onChange={e=>setTest(e.target.value)} placeholder="allowlisted test command"/><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder="Narrow task. No --yolo."/><button onClick={run}>Start audited run</button></>}<h3>Sessions</h3>{(sessions.d||[]).map((s:any)=><button className="rowbtn" onClick={()=>setSelected(s.id)} key={s.id}>{s.status} · {s.workspace}<small>{s.task}</small></button>)}</div><div className="panel"><h2>Live Session</h2><div className="bar"><button onClick={cancel}>Cancel</button><input value={commitMsg} onChange={e=>setCommitMsg(e.target.value)} placeholder="commit message"/><button onClick={commit}>Confirm Commit</button></div><Json data={{...session.d,log:undefined}}/><pre className="log">{session.d?.log||''}</pre></div></section>}
function KanbanPage(){const{d,refresh}=useData('/kanban/tasks');const[title,setTitle]=useState('');const add=async()=>{await post('/kanban/tasks',{title});setTitle('');refresh()};const cols=['Backlog','Ready','Running','Review','Done','Failed'];return <section><div className="bar"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New task"/><button onClick={add}>Add</button></div><div className="columns">{cols.map(c=><div className="col" key={c}><h3>{c}</h3>{(d||[]).filter((t:any)=>t.status===c).map((t:any)=><div className="task" key={t.id}>{t.title}<small>{t.workspace||''}</small></div>)}</div>)}</div></section>}
function Memory(){const{d,refresh}=useData('/memory');const[form,setForm]=useState({title:'',content:'',scope:'global',tags:''});const add=async()=>{await post('/memory',{...form,tags:form.tags.split(',').filter(Boolean)});refresh()};return <section className="twocol"><div className="panel"><h2>Add Memory</h2><input placeholder="title" onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="content" onChange={e=>setForm({...form,content:e.target.value})}/><input placeholder="tags comma-separated" onChange={e=>setForm({...form,tags:e.target.value})}/><button onClick={add}>Save</button></div><div className="panel"><Json data={d}/></div></section>}
function Audit({agent}:{agent?:string}){const[filter,setFilter]=useState(''),path='/audit'+(filter?'?status='+filter:'');const{d,refresh}=useData(path);return <section className="panel"><h2>Audit Timeline {agent&&<small>({agent})</small>}</h2><div className="bar"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="status filter: ok/failed"/><button onClick={refresh}>Apply</button><a className="linkbtn" href="/api/audit/export.jsonl">Export JSONL</a></div><Json data={d}/></section>}
function SettingsPage(){const{d,refresh}=useData('/settings/effective');return <section className="panel"><h2>Effective Settings</h2><p>Secrets are never displayed or stored here. Configure secret values in `.env` only.</p><button onClick={refresh}>Refresh</button><Json data={d}/></section>}
function Goals(){const{d,refresh}=useData('/goals');const[title,setTitle]=useState('');const add=async()=>{await post('/goals',{title,status:'Backlog'});setTitle('');refresh()};return <section className="panel"><h2>Goal Mode Records</h2><p>This creates/list goal records. Automatic decomposition into sub-agent tasks is still explicitly scaffolded.</p><div className="bar"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New goal"/><button onClick={add}>Create goal</button></div><Json data={d}/></section>}
function MCPs(){const{d,refresh}=useData('/mcps');const[name,setName]=useState('github'),[endpoint,setEndpoint]=useState('');const add=async()=>{await post('/mcps',{name,endpoint,enabled:false,status:'registered'});refresh()};return <section className="panel"><h2>MCP Registry</h2><p>Register/list MCP connectors. Runtime start/stop/remove is not yet implemented, so the UI labels this honestly.</p><div className="bar"><input value={name} onChange={e=>setName(e.target.value)} placeholder="name"/><input value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="endpoint/command optional"/><button onClick={add}>Register MCP</button></div><Json data={d}/></section>}
createRoot(document.getElementById('root')!).render(<Shell/>);
