import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Activity,Brain,Cpu,GitBranch,Home,Kanban as KanbanIcon,MessageSquare,Settings,Shield,Terminal,Target,Plug}from'lucide-react';
import{get,post,patch}from'./api/client';
import'./styles/app.css';

const nav=['Mission Control','Chat','Agents','Codex','Workspaces','Kanban','Memory','Skills Hub','Activity','Settings','Goals','MCPs'];
const icon:any={"Mission Control":Home,Chat:MessageSquare,Agents:Cpu,Codex:Terminal,Workspaces:GitBranch,Kanban:KanbanIcon,Memory:Brain,'Skills Hub':Shield,Activity:Activity,Settings:Settings,Goals:Target,MCPs:Plug};

function Shell(){const[page,setPage]=useState(nav[0]);return <div className="shell"><aside><div className="brand"><div className="orb"/> <div><b>Agentic OS</b><span>One process, every door</span></div></div>{nav.map(n=>{const I=icon[n];return <button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={18}/>{n}</button>})}<div className="hint">Synology: open via <b>NAS-LAN-IP:3737</b>. Backend binds 0.0.0.0.</div></aside><main><header><div><h1>{page}</h1><p>Local-first AI operations control plane for Robel's agentic workflow.</p></div><TokenBox/></header><Page name={page}/></main></div>}
function TokenBox(){const[t,setT]=useState(localStorage.getItem('agentic_token')||'');return <label className="token">Admin token<input type="password" value={t} onChange={e=>{setT(e.target.value);localStorage.setItem('agentic_token',e.target.value)}} placeholder="required for actions"/></label>}
function Page({name}:{name:string}){if(name==='Mission Control')return <Mission/>; if(name==='Chat')return <Chat/>; if(name==='Agents')return <List title="Agents" path="/agents"/>; if(name==='Codex')return <Codex/>; if(name==='Workspaces')return <List title="Workspaces" path="/workspaces"/>; if(name==='Kanban')return <KanbanPage/>; if(name==='Memory')return <Memory/>; if(name==='Skills Hub')return <List title="Skills" path="/skills"/>; if(name==='Activity')return <Audit/>; if(name==='Goals')return <Goals/>; if(name==='MCPs')return <MCPs/>; return <SettingsPage/>}
function useData(path:string, interval=0){const[d,setD]=useState<any>(null),[e,setE]=useState('');const refresh=()=>get(path).then(x=>{setD(x);setE('')}).catch(x=>setE(String(x)));useEffect(()=>{refresh(); if(interval){const id=setInterval(refresh,interval); return()=>clearInterval(id)}},[path,interval]);return{d,e,refresh}}
function Json({data}:{data:any}){return <pre>{JSON.stringify(data,null,2)}</pre>}
function Mission(){const{d,e}=useData('/systems/status',5000);return <section>{e&&<p className="err">{e}</p>}<div className="grid">{(d?.systems||[]).map((s:any)=><div className="card" key={s.name}><span className={s.enabled?'dot ok':'dot'}/><h3>{s.name}</h3><p>{s.provider}</p><b>{s.enabled?'Enabled':'Disabled'}</b><small>Sessions {s.active_sessions}</small></div>)}</div><div className="twocol wide"><div className="panel"><h2>Active processes</h2><Json data={d?.active_processes||[]}/></div><div className="panel"><h2>Recent failed actions</h2><Json data={d?.recent_failed_actions||[]}/></div></div></section>}
function List({title,path}:{title:string,path:string}){const{d,e}=useData(path);return <section className="panel"><h2>{title}</h2>{e&&<p className="err">{e}</p>}<Json data={d}/></section>}
function Chat(){const[threads,setThreads]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[msg,setMsg]=useState(''),[agent,setAgent]=useState('deepseek-chat'),[thread,setThread]=useState(''),[err,setErr]=useState('');const loadThreads=()=>get('/chat/threads').then(setThreads);useEffect(()=>{loadThreads()},[]);useEffect(()=>{if(thread)get('/chat/threads/'+thread).then(r=>setMessages(r.messages||[]))},[thread]);const send=async()=>{setErr('');try{const r=await post('/chat',{message:msg,agent,thread_id:thread||undefined});setThread(r.thread_id);setMsg('');await loadThreads();const t=await get('/chat/threads/'+r.thread_id);setMessages(t.messages||[])}catch(e:any){setErr(String(e))}};return <section className="twocol"><div className="panel"><h2>Threads</h2>{threads.map(t=><button className="rowbtn" key={t.id} onClick={()=>setThread(t.id)}>{t.title}<small>{t.agent} · {t.model}</small></button>)}</div><div className="panel"><h2>OpenAI-compatible Chat</h2><input value={agent} onChange={e=>setAgent(e.target.value)} placeholder="agent"/><div className="chatbox">{messages.map(m=><div className={'msg '+m.role} key={m.id}><b>{m.role}</b><p>{m.content}</p></div>)}</div><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Ask DeepSeek/OpenWebUI..."/><button onClick={send}>Send</button>{err&&<p className="err">{err}</p>}</div></section>}
function Codex(){const[task,setTask]=useState(''),[workspace,setWorkspace]=useState('agentic-os'),[branch,setBranch]=useState(''),[test,setTest]=useState(''),[selected,setSelected]=useState(''),[commitMsg,setCommitMsg]=useState('');const sessions=useData('/codex/sessions',3000);const session=useData(selected?'/codex/sessions/'+selected:'/codex/sessions',selected?2000:0);const run=async()=>{const r=await post('/codex/run',{task,workspace,branch:branch||undefined,test_command:test||undefined,auto_commit:false,background:true});setSelected(r.id)};const cancel=()=>selected&&post('/codex/sessions/'+selected+'/cancel',{});const commit=()=>selected&&post('/codex/sessions/'+selected+'/commit',{confirm:true,message:commitMsg||'codex: apply session changes'});return <section className="twocol"><div className="panel"><h2>Start Codex task</h2><input value={workspace} onChange={e=>setWorkspace(e.target.value)} placeholder="workspace"/><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="branch optional"/><input value={test} onChange={e=>setTest(e.target.value)} placeholder="allowlisted test command"/><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder="Narrow task. No --yolo."/><button onClick={run}>Start audited run</button><h3>Sessions</h3>{(sessions.d||[]).map((s:any)=><button className="rowbtn" onClick={()=>setSelected(s.id)} key={s.id}>{s.status} · {s.workspace}<small>{s.task}</small></button>)}</div><div className="panel"><h2>Live Session</h2><div className="bar"><button onClick={cancel}>Cancel</button><input value={commitMsg} onChange={e=>setCommitMsg(e.target.value)} placeholder="commit message"/><button onClick={commit}>Confirm Commit</button></div><Json data={{...session.d,log:undefined}}/><pre className="log">{session.d?.log||''}</pre></div></section>}
function KanbanPage(){const{d,refresh}=useData('/kanban/tasks');const[title,setTitle]=useState('');const add=async()=>{await post('/kanban/tasks',{title});setTitle('');refresh()};const cols=['Backlog','Ready','Running','Review','Done','Failed'];return <section><div className="bar"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New task"/><button onClick={add}>Add</button></div><div className="columns">{cols.map(c=><div className="col" key={c}><h3>{c}</h3>{(d||[]).filter((t:any)=>t.status===c).map((t:any)=><div className="task" key={t.id}>{t.title}<small>{t.workspace||''}</small></div>)}</div>)}</div></section>}
function Memory(){const{d,refresh}=useData('/memory');const[form,setForm]=useState({title:'',content:'',scope:'global',tags:''});const add=async()=>{await post('/memory',{...form,tags:form.tags.split(',').filter(Boolean)});refresh()};return <section className="twocol"><div className="panel"><h2>Add Memory</h2><input placeholder="title" onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="content" onChange={e=>setForm({...form,content:e.target.value})}/><input placeholder="tags comma-separated" onChange={e=>setForm({...form,tags:e.target.value})}/><button onClick={add}>Save</button></div><div className="panel"><Json data={d}/></div></section>}
function Audit(){const[filter,setFilter]=useState(''),{d,refresh}=useData('/audit'+(filter?'?status='+filter:''));return <section className="panel"><h2>Audit Timeline</h2><div className="bar"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="status filter: ok/failed"/><button onClick={refresh}>Apply</button><a className="linkbtn" href="/api/audit/export.jsonl">Export JSONL</a></div><Json data={d}/></section>}
function SettingsPage(){const{d,refresh}=useData('/settings/effective');return <section className="panel"><h2>Effective Settings</h2><p>Secrets are never displayed or stored here. Configure secret values in `.env` only.</p><button onClick={refresh}>Refresh</button><Json data={d}/></section>}
function Goals(){const{d,refresh}=useData('/goals');const[title,setTitle]=useState('');const add=async()=>{await post('/goals',{title,status:'Backlog'});setTitle('');refresh()};return <section className="panel"><h2>Goal Mode Scaffold</h2><div className="bar"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New goal"/><button onClick={add}>Create goal</button></div><Json data={d}/></section>}
function MCPs(){const{d,refresh}=useData('/mcps');const[name,setName]=useState('github');const add=async()=>{await post('/mcps',{name,status:'placeholder'});refresh()};return <section className="panel"><h2>MCP Registry</h2><p>Runtime management is scaffolded; connectors stay disabled until configured.</p><div className="bar"><input value={name} onChange={e=>setName(e.target.value)}/><button onClick={add}>Register placeholder</button></div><Json data={d}/></section>}
createRoot(document.getElementById('root')!).render(<Shell/>);
