import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Activity,Brain,Cpu,GitBranch,Home,Kanban as KanbanIcon,MessageSquare,Settings,Shield,Terminal}from'lucide-react';
import{get,post}from'./api/client';
import'./styles/app.css';
const nav=['Mission Control','Chat','Agents','Codex','Workspaces','Kanban','Memory','Skills Hub','Activity','Settings'];
const icon:any={"Mission Control":Home,Chat:MessageSquare,Agents:Cpu,Codex:Terminal,Workspaces:GitBranch,Kanban:KanbanIcon,Memory:Brain,'Skills Hub':Shield,Activity:Activity,Settings:Settings};
function Shell(){const[page,setPage]=useState(nav[0]);return <div className="shell"><aside><div className="brand"><div className="orb"/> <div><b>Agentic OS</b><span>One process, every door</span></div></div>{nav.map(n=>{const I=icon[n];return <button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={18}/>{n}</button>})}</aside><main><header><div><h1>{page}</h1><p>Local-first AI operations control plane for Robel's agentic workflow.</p></div><TokenBox/></header><Page name={page}/></main></div>}
function TokenBox(){const[t,setT]=useState(localStorage.getItem('agentic_token')||'');return <label className="token">Admin token<input type="password" value={t} onChange={e=>{setT(e.target.value);localStorage.setItem('agentic_token',e.target.value)}} placeholder="required for actions"/></label>}
function Page({name}:{name:string}){if(name==='Mission Control')return <Mission/>; if(name==='Chat')return <Chat/>; if(name==='Agents')return <List title="Agents" path="/agents"/>; if(name==='Codex')return <Codex/>; if(name==='Workspaces')return <List title="Workspaces" path="/workspaces"/>; if(name==='Kanban')return <KanbanPage/>; if(name==='Memory')return <Memory/>; if(name==='Skills Hub')return <List title="Skills" path="/skills"/>; if(name==='Activity')return <List title="Audit" path="/audit"/>; return <List title="Effective Settings" path="/settings/effective"/>}
function useData(path:string){const[d,setD]=useState<any>(null),[e,setE]=useState('');const refresh=()=>get(path).then(setD).catch(x=>setE(String(x)));useEffect(()=>{refresh()},[path]);return{d,e,refresh}}
function Mission(){const{d,e}=useData('/systems/status');return <section>{e&&<p className="err">{e}</p>}<div className="grid">{(d?.systems||[]).map((s:any)=><div className="card" key={s.name}><span className={s.enabled?'dot ok':'dot'}/><h3>{s.name}</h3><p>{s.provider}</p><b>{s.enabled?'Enabled':'Disabled'}</b><small>Latency {s.latency_ms??'n/a'} · Sessions {s.active_sessions}</small></div>)}</div><div className="panel"><h2>Recent failed actions</h2><pre>{JSON.stringify(d?.recent_failed_actions||[],null,2)}</pre></div></section>}
function List({title,path}:{title:string,path:string}){const{d,e}=useData(path);return <section className="panel"><h2>{title}</h2>{e&&<p className="err">{e}</p>}<pre>{JSON.stringify(d,null,2)}</pre></section>}
function Chat(){const[msg,setMsg]=useState(''),[agent,setAgent]=useState('deepseek-chat'),[thread,setThread]=useState(''),[out,setOut]=useState('');const send=async()=>{const r=await post('/chat',{message:msg,agent,thread_id:thread||undefined});setThread(r.thread_id);setOut(r.message)};return <section className="twocol"><div className="panel"><h2>Local Chat</h2><input value={agent} onChange={e=>setAgent(e.target.value)}/><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Ask DeepSeek/OpenWebUI..."/><button onClick={send}>Send</button></div><div className="panel"><h2>Response</h2><p>{out}</p></div></section>}
function Codex(){const[task,setTask]=useState(''),[workspace,setWorkspace]=useState('agentic-os'),[branch,setBranch]=useState(''),[test,setTest]=useState(''),[session,setSession]=useState<any>(null);const run=async()=>setSession(await post('/codex/run',{task,workspace,branch:branch||undefined,test_command:test||undefined,auto_commit:false,background:true}));return <section className="twocol"><div className="panel"><h2>Start Codex task</h2><input value={workspace} onChange={e=>setWorkspace(e.target.value)} placeholder="workspace"/><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="branch optional"/><input value={test} onChange={e=>setTest(e.target.value)} placeholder="test command optional"/><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder="Narrow task. No --yolo."/><button onClick={run}>Start audited run</button></div><div className="panel"><h2>Session</h2><pre>{JSON.stringify(session,null,2)}</pre></div></section>}
function KanbanPage(){const{d,refresh}=useData('/kanban/tasks');const[title,setTitle]=useState('');const add=async()=>{await post('/kanban/tasks',{title});setTitle('');refresh()};const cols=['Backlog','Ready','Running','Review','Done','Failed'];return <section><div className="bar"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New task"/><button onClick={add}>Add</button></div><div className="columns">{cols.map(c=><div className="col" key={c}><h3>{c}</h3>{(d||[]).filter((t:any)=>t.status===c).map((t:any)=><div className="task" key={t.id}>{t.title}</div>)}</div>)}</div></section>}
function Memory(){const{d,refresh}=useData('/memory');const[form,setForm]=useState({title:'',content:'',scope:'global',tags:''});const add=async()=>{await post('/memory',{...form,tags:form.tags.split(',').filter(Boolean)});refresh()};return <section className="twocol"><div className="panel"><h2>Add Memory</h2><input placeholder="title" onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="content" onChange={e=>setForm({...form,content:e.target.value})}/><input placeholder="tags comma-separated" onChange={e=>setForm({...form,tags:e.target.value})}/><button onClick={add}>Save</button></div><div className="panel"><pre>{JSON.stringify(d,null,2)}</pre></div></section>}
createRoot(document.getElementById('root')!).render(<Shell/>);
